### PR TITLE
Reqwest without openssl

### PR DESCRIPTION
**Pull request by ssrlive**

### CODE REVIEW

**Comment by blechschmidt** [comment]
Unfortunately, this breaks the tests because rustls only supports IP addresses in TLS certificates in a not yet released version, cf. https://github.com/rustls/rustls/issues/184#issuecomment-1385458603. Therefore, the connection to https://1.1.1.1 fails. Since DNS is not supported without helpers yet, it cannot be simply fixed by using a domain name and updating `/etc/resolv.conf`.

**Comment by ssrlive** [comment]
OK. Once the new versions of reqwest and rustls released, I will reopen this PR again.

**Comment by blechschmidt** [comment]
Sounds good.

**Comment by ssrlive** [comment]
I find that rustls have upgraded. can we merge this patch?

**Comment by blechschmidt** [comment]
Yup, done.

**Pull request merged**
