### PR TITLE
Initial support for digest auth scheme

### PR DESCRIPTION
**Pull request by jorgeajimenezl**
Issue #43

Actually this works after the second request (when it gets the proxy challenge parameters). This must be because I made some mistake while restarting the connection. The workflow should be something like this (at the start of the program): 

1. tun2proxy makes the request using the basic authentication scheme 
2. The server returns a 407 error with the `Proxy-Authenticate` tag and the challenge digest parameters. 
3. If the server specifies `Connection: close` or does not specify any header nor `Content-Length` or `Transfer-Encoding` then the connection is closed and restarted. Otherwise, it determines the size of the current HTTP frame and jumps to it. 
3. tun2proxy now sends the request using the authentication digest with the response values to the challenge.
4. For next request tun2proxy holds the old `nonce` param and use it to authenticate the response until the proxy requests by a new one, so, reset the connection with the proxy isn't longer needed

### CODE REVIEW

**Comment by blechschmidt** [comment]
Don't worry about the CI failures, they have nothing to do with your changes. I am currently in the process of reviewing this PR and will get back to you afterwards.

**Comment by blechschmidt** [comment]
Thanks a lot for your contribution! I finally found some time to review and test the code with a squid server.

> Actually this works after the second request (when it gets the proxy challenge parameters). This must be because I made some mistake while restarting the connection.

I am not sure I understand why you think you made a mistake. In my test, everything worked fine and the packet capture looks good as well: https://gist.github.com/blechschmidt/9163003e91e4d3e4abbcff62fa4a091f/raw/e3deeb91c17b2e5193107a2dd8f9bd8b1873a098/digest-auth.pcapng

**Comment by jorgeajimenezl** [comment]
Thanks to you for the review and accept this.

> I am not sure I understand why you think you made a mistake. In my test, everything worked fine and the packet capture looks good as well:

I see that in the squid configuration you used the server responds `407` but does not close the connection. In this case everything works normal, and there is no error, tun2proxy just needs to determine the end of the request and wait there for more content. You have to specify to close the connection (I tried it with my university's squid which has this behavior) to force tun2proxy to restart the connection with squid.  In these days I will see if I can make this test replicable and send the `squid.conf` for testing.

**Comment by blechschmidt** [comment]
I see. I could now reproduce it with the following config:
```
http_port 4080
via off
cache deny all
 
auth_param digest program /usr/lib/squid/digest_file_auth -c /etc/squid/passwd_digest
auth_param digest children 5
auth_param digest credentialsttl 2 hours
auth_param digest casesensitive on
auth_param digest realm tun2proxy
acl auth_users proxy_auth REQUIRED
 
http_access allow auth_users
http_access deny all

client_persistent_connections off
```
(modified from https://suay.site/?p=1250)

**Comment by blechschmidt** [comment]
3e26675919877d834bb2e15482c0b60cfb07734a should fix this.

The relevant part is to advance the state here:
https://github.com/blechschmidt/tun2proxy/blob/3e26675919877d834bb2e15482c0b60cfb07734a/src/http.rs#L314

The `state_change` function is only called when data is pushed. Without this change, the following happens:

- The HTTP state of the `HTTPConection` is set to `Reset`.
- The tunnel request will be sent.
- A reply will be received and the `HTTPConnection` is in the reset state.
- Inside `state_change`, the HTTP state is now set to `ExpectResponseHeaders`.
- But `state_change` is not called again, so this state is never really handled.

**Comment by jorgeajimenezl** [comment]
Perfect, thank you very much for your fix, and once again congratulations for such a great app. 👏🏻 👏🏻

**Pull request merged**
