### PR TITLE
XCFramework build for apple

### PR DESCRIPTION
**Pull request by EbrahimTahernejad**

### CODE REVIEW

**Comment by ssrlive** [comment]
If I agree to this PR, the compilation results on macos will no longer be available. Can you suggest a better solution?

I mean, what do you think about only supporting compilation to xcframework for ios and leaving the compilation target on macos unchanged? Refer to the contents of the `apple` folder.

**Comment by EbrahimTahernejad** [comment]
I do agree that this isn't a good solution for macOS. But I believe it needs to support both binary and xcframework. 
However, I know nothing about Rust (it's my first time touching a Rust code) so I can't go further to fix this for macOS.
And yes, I could only build for iOS, but I think having it for Mac as well would be convenient as the NetworkExtension is supported in both iOS and macOS as a user-level solution for creating a tun interface.

**Comment by ssrlive** [comment]
now, try to build with your script. have a look?

**Comment by ssrlive** [comment]
now, try to build with your script. have a look?
and if you success, please test it in your project with a real iPhone.

**Comment by ssrlive** [comment]
Please report your testing result here.

**Comment by EbrahimTahernejad** [comment]
Will do in a bit

**Comment by ssrlive** [comment]
well. I will merge it first.

**Comment by ssrlive** [comment]
Hi @EbrahimTahernejad , I have test it on IOS platform. Can you create another script to build for Android? Thanks.

**Comment by EbrahimTahernejad** [comment]
Sorry, I was really busy with some irl stuff I forgot about testing this.
Glad to hear it's working.

I'm not that much of an android guy tbh but I'll try.

**Comment by EbrahimTahernejad** [comment]
Hey @ssrlive 

Sorry, I was really busy with some irl stuff I forgot about testing this.
Glad to hear it's working.

I'm not that much of an android guy tbh but I'll try.

**Pull request merged**
