### PR TITLE
Udp deal

### PR DESCRIPTION
**Pull request by ssrlive**
Hi @blechschmidt , I have merged your UDP code to this branch. But I think it is not work. so I need your help.

1. tun0  incoming  -> 
2. udp packet -> 
3. tun2proxy connect s5 server with tcp to request a udp random  addr:port ->
4. tun2proxy traffic udp data to the s5 responded udp addr:port with S5 UDP data format
5. close the tcp connection in step 3, thus indicated the full udp session completed.

### CODE REVIEW

**Comment by blechschmidt** [comment]
The implementation was not finished, that's why it wasn't merged.

I am not sure I correctly got your understanding of step 3, that's why I will quickly describe my understanding here (in particular of what is your third step):
1. You send an `UDP Associate` request to the SOCKS5 server. As you noted, this is a TCP request. However, **in that request, you do not specify the destination address of the UDP packet**. [RFC 1928](https://www.rfc-editor.org/rfc/rfc1928) states that the "DST.ADDR and DST.PORT fields contain the address and port that the client expects to use to send UDP datagrams on for the association". Since many clients are behind NAT nowadays and cannot easily determine their IP address without external helpers, it should be fine to generally follow this procedure described in the RFC: "If the client is not in possesion of the information at the time of the UDP ASSOCIATE, the client MUST use a port number and address of all zeros."
Therefore the request should look exactly like this:
    ```
    
    +----+-----+-------+------+------------+----------+
    |VER | CMD |  RSV  | ATYP | DST.ADDR   | DST.PORT |
    +----+-----+-------+------+------------+----------+
    |0x05| 0x3 |  0x0  | 0x01 | 0x00000000 |  0x0000  |
    +----+-----+-------+------+------------+----------+
    ```
2. You will receive a reply with `BND.ADDR` and `BND.PORT`. This is where you send the UDP packets to in the corresponding SOCKS5 UDP format as soon as a UDP packet arrives at the tunnel interface. Packets to any destination will go there, i.e. you don't need a new `UDP Associate` request for a new UDP "connection" (UDP is connectionless, I mean a tuple consisting of source and destination endpoints here, you get it).


For better efficiency one could already perform the UDP association at program startup and close it upon termination.

**Comment by ssrlive** [comment]
When there is a TCP long connection, it may be terminated by the operating system or network equipment. If you use the program to connect until the end of the program, then the intermediate tcp long connection may be interrupted, so reconnection must be considered. mechanism.

So what I mean is, to simplify programming, it is better to create a udp association connection for a udp packet request. Anyway, the overall amount of udp data transmission is very small.

> For better efficiency one could already perform the UDP association at program startup and close it upon termination.

**Comment by ssrlive** [comment]
When the client asks the s5 server to listen the specified addr:port provided by client, the s5 server generally ignores it, and the s5 server usually specifies a random udp addr:port for the client to use.

image

**Comment by blechschmidt** [comment]
> For better efficiency one could already perform the UDP association at program startup and close it upon termination.

I was wrong about that anyway, sorry. You would need one UDP association per source and destination endpoint tuple. Otherwise you will run into problems with UDP traffic to the same destination endpoint. (Assume you have two VoIP connections to the same UDP endpoint. With my proposal you wouldn't be able distinguish the two.)

> When there is a long TCP connection, it may be terminated by the operating system or network equipment. If you use tcp to connect to the socks5 server at the beginning of the program and then disconnect it until the end of the program, then the long tcp connection may be interrupted during this period , so the mechanism for reconnection must be considered.
Depending on how long your UDP connection lasts, you will have that problem anyway. As an example, a VoIP session could be alive for several hours. But this should be solvable using TCP keepalives. As it seems, `mio::net::TcpStream` doesn't currently expose keepalives, but it should be doable through the raw file descriptors using `SO_KEEPALIVE and `TCP_KEEPALIVE` or `TCP_KEEPIDLE` options.

> So what I mean is that in order to simplify programming, it is better to create a udp associated connection (TCP) for each udp packet request. Anyway, the overall amount of udp data transmission is very small.

If "packet request" refers to a source and destination endpoint tuple, that sounds about right and seems to be the only way. In general I would set up a timeout of about one minute after which the connection is closed and reset that timeout whenever a packet belonging to the connection goes out or comes in.

(Regarding performance, one could pre-pool UDP association requests, as well as TCP connections to eliminate the handshake/authentication round trip times, but that would be something optional after tun2proxy is feature-complete.)

**Pull request merged**
